### ISSUE TITLE
Ran into a problem when running CA-NAC

### ISSUE THREAD

**Issue by XiankeYue** [WeibinChu/CA-NAC#3]
![image](https://github.com/WeibinChu/CA-NAC/assets/94552386/3234c89d-0d17-4d49-80fd-4b927082dbd5)
How do I solve this?

**Comment by Palakchugh21** [comment]
I am facing the same problem. Can you please help

**Comment by WeibinChu** [comment]
> I am facing the same problem. Can you please help

Ensure the POTCAR file is present in your working directory (where you execute VASP commands). If following the tutorial, copy the POTCAR file to the parent directory

**Comment by Palakchugh21** [comment]
"Thank you for your help! I am now encountering a different issue now—the code is searching for NORMALCAR, but VASP does not generate this file. Could you please advise on how to proceed?"

**Comment by WeibinChu** [comment]
> "Thank you for your help! I am now encountering a different issue now—the code is searching for NORMALCAR, but VASP does not generate this file. Could you please advise on how to proceed?"

Please check the prerequisites in the README, or simply set is_alle = False to disable the all-electron correction.

**Comment by Palakchugh21** [comment]
Thank you so much for your help! That issue is resolved. Now, as I move forward with NAMD, I’m a bit confused about generating the INICON file. Could you guide me on how to create it?

**Comment by Palakchugh21** [comment]
I’m a bit confused about generating the INICON file. Could you guide me on how to create it?

**Comment by Palakchugh21** [comment]
"I am encountering an error at line 356 of the file couplings.f90 (unit = 23, file = 'NATXT') with the message: 'Fortran runtime error: Bad complex value in item 1 of list input.' Even though my data is generated from the output of CA-NAC, when I run the Hefei-NAMD module using the DiSH algorithm, it fails to read the NATXT file and gives this error. Could you please help me understand the reason for this issue?
